### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by RedX2501** [SoulcodeAgency/vscode-unwanted-extensions#6]
The Marketplace https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions

Shows releases 1.1.2 and 1.1.1 and others which don't have a tag in this repo.

I wanted to look at the code for 1.1.2 to understand why there is a recommendations in `extensionsVersionCheck.json` when nothing happens (separate ticket).

I cannot because the tags with these releases are missing.

**Comment by Cyclodex** [comment]
The tags are not pushed yet, because they are pre-releases and on the dev branch. I will push them when the release is stable and merged to main.

You will find them on the dev branch easily if you want to check them.

As already mentioned in the other task, there is not "recommendations" implemented yet, as the focus is (currently) on unwanted recommendations. But maybe we will use the the recommendations in the future and implement features for that as well.

Feel free to help discuss topics / features, or contribute whatever this extensions topics would improve.

I close this ticket as done.
